<?php

namespace ElasticKit\Index;

use RuntimeException;
use stdClass;

/**
 * Zero-downtime index rebuild: create backing index, import data, swap alias.
 *
 * $name is always the app-facing name. After rebuild, $name becomes an alias
 * pointing to a backing index generated by rebuildName().
 */
class Rebuild
{
    /**
     * @var Index
     */
    private $index;

    /**
     * @var int
     */
    private $batchSize = 1000;

    /**
     * @var bool
     */
    private $skipErrors = false;

    /**
     * @var bool
     */
    private $allowEmpty = false;

    /**
     * @var callable|\Iterator<int, array<string, mixed>>|null
     */
    private $dataSource;

    /**
     * @param Index $index
     */
    public function __construct(Index $index)
    {
        $this->index = $index;
    }

    /**
     * Set the batch size for bulk import. Defaults to 1000.
     *
     * @param int $size
     * @return $this
     */
    public function batchSize($size)
    {
        $this->batchSize = $size;
        return $this;
    }

    /**
     * Skip bulk import errors instead of throwing. Defaults to false.
     *
     * @param bool $skip
     * @return $this
     */
    public function skipErrors($skip = true)
    {
        $this->skipErrors = $skip;
        return $this;
    }

    /**
     * Allow importing zero documents without throwing. Defaults to false.
     *
     * @param bool $allow
     * @return $this
     */
    public function allowEmpty($allow = true)
    {
        $this->allowEmpty = $allow;
        return $this;
    }

    /**
     * Set a custom data source. Accepts a callable or iterable.
     * Defaults to Index::source() when not set.
     *
     * @param callable|\Iterator<int, array<string, mixed>> $source
     * @return $this
     */
    public function source($source)
    {
        $this->dataSource = $source;
        return $this;
    }

    /**
     * Run the rebuild: create backing index -> import data -> swap alias.
     *
     * Handles three scenarios:
     * - $name is already an alias: atomic swap (zero downtime)
     * - $name is a real index: throws RuntimeException (convert to alias mode first)
     * - $name does not exist: create alias pointing to new backing index
     *
     * @param array<string, mixed> $context user-defined context passed to source()
     * @return array{newIndex: string, oldIndex: string|null}
     */
    public function run(array $context = [])
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        Index::dispatch(new Event('rebuild.run.before', $name));

        $newName = $this->createIndex();

        try {
            $this->import($newName, $context);
        } catch (\Throwable $e) {
            $client->delete(['index' => $newName]);
            throw $e;
        }

        $client->refresh(['index' => $newName]);

        $oldIndex = null;

        if ($client->existsAlias(['name' => $name])->asBool()) {
            $oldIndices = array_keys($client->getAlias(['name' => $name])->asArray());
            $oldIndex = $oldIndices[0] ?? null;
            $actions = [];
            foreach ($oldIndices as $idx) {
                $actions[] = ['remove' => ['index' => $idx, 'alias' => $name]];
            }
            $actions[] = ['add' => ['index' => $newName, 'alias' => $name]];
            $client->updateAliases(['body' => ['actions' => $actions]]);
        } elseif ($client->exists(['index' => $name])->asBool()) {
            $client->delete(['index' => $newName]);
            throw new RuntimeException(
                "Index [{$name}] is a real index, not an alias. "
                . "Rebuild requires an alias to swap atomically. "
                . "Delete the index manually or convert it to alias mode before running rebuild."
            );
        } else {
            $client->putAlias(['index' => $newName, 'name' => $name]);
        }

        $e = new Event('rebuild.run.after', $name);
        $e->newIndex = $newName;
        $e->oldIndex = $oldIndex;
        Index::dispatch($e);

        return ['newIndex' => $newName, 'oldIndex' => $oldIndex];
    }

    /**
     * Delete a specific backing index by name.
     *
     * @param string $indexName the backing index to delete
     */
    public function clean(string $indexName): void
    {
        $this->index->getClient()->indices()->delete([
            'index' => $indexName,
        ]);
    }

    /**
     * Rollback alias to a specific previous backing index.
     *
     * @param string $targetIndex the backing index to roll back to
     * @return string the index name that was rolled back from
     * @throws RuntimeException if alias or target index does not exist
     */
    public function rollback(string $targetIndex): string
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        $currentList = array_keys($client->getAlias(['name' => $name])->asArray());
        if (empty($currentList)) {
            throw new RuntimeException("No index found for alias [{$name}]");
        }

        if (!$client->exists(['index' => $targetIndex])->asBool()) {
            throw new RuntimeException("Target index [{$targetIndex}] does not exist");
        }

        $client->updateAliases([
            'body' => [
                'actions' => [
                    ['remove' => ['index' => $currentList[0], 'alias' => $name]],
                    ['add' => ['index' => $targetIndex, 'alias' => $name]],
                ],
            ],
        ]);

        return $currentList[0];
    }

    /**
     * Create a new backing index using mappings/settings from the Index subclass.
     *
     * @return string the new backing index name
     */
    protected function createIndex()
    {
        $newName = $this->index->rebuildName();
        $mappings = $this->index->mappings();
        $settings = $this->index->settings();

        $this->index->getClient()->indices()->create([
            'index' => $newName,
            'body' => [
                'mappings' => empty($mappings) ? new stdClass() : $mappings,
                'settings' => empty($settings) ? new stdClass() : $settings,
            ],
        ]);

        return $newName;
    }

    /**
     * Import data into the target index.
     *
     * @param string $newName
     * @param array<string, mixed> $context
     */
    protected function import($newName, array $context): void
    {
        if ($this->dataSource !== null) {
            $items = is_callable($this->dataSource) ? ($this->dataSource)($context) : $this->dataSource;
        } else {
            $items = $this->index->source($context);
        }

        $bulk = (new Bulk($this->index))->target($newName)->batchSize($this->batchSize);
        $count = 0;
        foreach ($items as $id => $doc) {
            if (!is_array($doc)) {
                throw new RuntimeException(
                    "source() must yield [id => document] pairs, got non-array value for key [{$id}]. "
                    . "Expected: yield \$id => ['field' => 'value'], got \$id => " . gettype($doc)
                );
            }
            $bulk->index($id, $doc);
            $count++;
        }

        if ($count === 0 && !$this->allowEmpty) {
            throw new RuntimeException(
                "Rebuild imported 0 documents for index [{$newName}]. "
                . "Call allowEmpty() if this is intentional."
            );
        }

        $response = $bulk->execute();

        if (!empty($response['errors'])) {
            $e = new Event('rebuild.import.failed', $this->index->name());
            $e->response = $response;
            Index::dispatch($e);

            if (!$this->skipErrors) {
                $json = json_encode($response, JSON_UNESCAPED_UNICODE);
                if (strlen($json) > 4096) {
                    $json = substr($json, 0, 4096) . '... [truncated]';
                }
                throw new RuntimeException("Bulk import failed for index [{$newName}]: {$json}");
            }
        }
    }
}
